### ISSUE TITLE
some usage examples

### ISSUE THREAD

**Issue by codefist** [taxfix/grakn_elixir#22]
I'm VERY fresh to grakn, and sorta fresh to elixir.
It would be very very useful if you could toss just a couple lines of example usage into the readme.
thanks

**Comment by liveforeverx** [comment]
@codefist Thank you for a good suggestion. We will do it.

At the time being, you can check tests for usage examples.

**Comment by codefist** [comment]
@liveforeverx I am, but i'm such a noob, haha.  Also, you show the mix configuration, but I don't know the way, or best practice on how to maintain the conn within a phoenix app.  Do i somehow boot up the connection as a genserver?

**Comment by liveforeverx** [comment]
@codefist 

You just add `{Grakn, [name: MyApp.Grakn] ++ opts}` to a supervision tree. After application is booted, you can use this name for accessing this process: `Grakn.transaction(MyApp.Grakn, ....)`
